---
- name: Provision RDS Database
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Install MySQL Client
      apt:
        name: mysql-client
        state: present

